spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    com.github.arhor: DEBUG
