spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    com.github.arhor: DEBUG

configuration:
  notifications:
    enabled: false
