spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env.local[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../.env.local[.properties]

application-props:
  log-method-execution: true
