name: Client CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'app-models/**'
      - 'app-client/**'
      - '!app-models/*.md'
      - '!app-client/*.md'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app-models/**'
      - 'app-client/**'
      - '!app-models/*.md'
      - '!app-client/*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          cache: 'npm'
          cache-dependency-path: |
            app-models/package-lock.json
            app-client/package-lock.json

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        env:
          DOWNLOAD_NODE: false

      - name: Build client-side app
        run: './gradlew :app-client:build'
