name: Server CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'app-model/**'
      - 'app-server/**'
      - '!app-server/*.md'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app-model/**'
      - 'app-server/**'
      - '!app-server/*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build server-side app
        run: './gradlew :app-server:build'
