name: Server CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'app-schema/**'
      - 'app-server/**'
      - '!app-schema/*.md'
      - '!app-server/*.md'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app-schema/**'
      - 'app-server/**'
      - '!app-schema/*.md'
      - '!app-server/*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          cache: 'npm'
          cache-dependency-path: |
            app-schema/package-lock.json

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build server-side app
        run: './gradlew :apps:server:build'
        env:
          DOWNLOAD_NODE: false
